services:
  proxylitechecker:
    image: ghcr.io/ry-zzcn/proxylitechecker:v0.4.2
    build: .
    container_name: proxylitechecker
    restart: unless-stopped
    env_file:
      - path: .env
        required: false
    environment:
      TZ: Asia/Shanghai
    ports:
      - "8899:8899"
      - "18080-18089:18080-18089"
    volumes:
      - ./data:/app/data
