services:
  proxylitechecker:
    image: ghcr.io/ry-zzcn/proxylitechecker:v0.1.6
    build: .
    container_name: proxylitechecker
    restart: unless-stopped
    env_file:
      - path: .env
        required: false
    ports:
      - "8899:8899"
      - "18080:18080"
      - "18081:18081"
    volumes:
      - ./data:/app/data
